name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: run tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: run gofmt
        run: test -z $(go fmt ./...)

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1

  tags:
    name: Check tags
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #fetch tags

      - name: fetch all tags
        run: git fetch --tags

      - name: Check if commit is tagged
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)

          if ! git describe --exact-match --tags $COMMIT_HASH; then
            echo "Commit is not tagged"
            exit 1
          fi
